version: "3.9"
services:
  global-cinema-mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - global-cinema-network
    volumes:
      - ${PWD}:/data/db
  global-cinema-redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - global-cinema-network
networks:
  global-cinema-network:
    driver: bridge
