version: "3.9"
services:
  global-cinema-service:
    image: global-cinema-service
    environment:
    - MODE=production
    networks:
      - global-cinema-network
    deploy:
      replicas: 5
  global-cinema-mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - global-cinema-network
    volumes:
      - ${PWD}:/data/db
  global-cinema-redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - global-cinema-network
  global-cinema-nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - global-cinema-service
      - global-cinema-client
    networks:
      - global-cinema-network
  global-cinema-client:
    image: global-cinema-client
    networks:
    - global-cinema-network
networks:
  global-cinema-network:
    driver: bridge
