database:
  port: 27017
  addr: localhost
  password: password
  user: admin
  dbName: global-cinema
  strConn: mongodb://admin:password@localhost:27017/test?authSource=admin
redis:
  port: 6379
  addr: localhost
  password:
  user:
  dbName: 0
  strConn: localhost:6379
