database:
  port: 27017
  addr: global-cinema-mongodb
  password: user
  user: admin
  dbName: global-cinema
  strConn: mongodb://admin:password@global-cinema-mongodb:27017/test?authSource=admin
redis:
  port: 6379
  addr: global-cinema-redis
  password:
  user:
  dbName: 0
  strConn: global-cinema-redis:6379
